### ISSUE TITLE
ValueError: Namespace OSTree not available

### ISSUE THREAD

**Issue by cinquecento** [rhinstaller/anaconda#201]
```
$ liveinst 
Starting installer, one moment...
Traceback (most recent call last):
  File "/sbin/anaconda", line 865, in <module>
    from pyanaconda import kickstart
  File "/usr/lib64/python3.4/site-packages/pyanaconda/kickstart.py", line 65, in <module>
    from pyanaconda.bootloader import GRUB2, get_bootloader
  File "/usr/lib64/python3.4/site-packages/pyanaconda/bootloader.py", line 42, in <module>
    from pyanaconda.packaging.rpmostreepayload import RPMOSTreePayload
  File "/usr/lib64/python3.4/site-packages/pyanaconda/packaging/rpmostreepayload.py", line 35, in <module>
    gi.require_version("OSTree", "1.0")
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace OSTree not available

$ anaconda --version
anaconda 23.14-1
```

**Comment by cinquecento** [comment]
With the ostree installed, it is resolved.

Next issue...
