### ISSUE TITLE
blivet.errors.DeviceTreeError: no slaves found for device md125

### ISSUE THREAD

**Issue by cinquecento** [rhinstaller/anaconda#213]
```
anaconda 23.15-1 exception report
Traceback (most recent call first):
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 245, in _addSlaveDevices
    raise DeviceTreeError("no slaves found for device %s" % name)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 363, in addUdevMDDevice
    self._addSlaveDevices(info)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 715, in addUdevDevice
    device = self.addUdevMDDevice(info)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 1659, in _populate
    self.addUdevDevice(dev)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 1596, in populate
    self._populate()
  File "/usr/lib/python3.4/site-packages/blivet/devicetree.py", line 554, in populate
    self._populator.populate(cleanupOnly=cleanupOnly)
  File "/usr/lib/python3.4/site-packages/blivet/blivet.py", line 279, in reset
    self.devicetree.populate(cleanupOnly=cleanupOnly)
  File "/usr/lib/python3.4/site-packages/blivet/osinstall.py", line 1123, in storageInitialize
    storage.reset()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 247, in run
    threading.Thread.run(self, *args, **kwargs)
blivet.errors.DeviceTreeError: no slaves found for device md125

Local variables in innermost frame:
name: md125
slave_devices: []
slave_dir: /sys/devices/virtual/block/md125/slaves
sysfs_path: /sys/devices/virtual/block/md125
self: <blivet.populator.Populator object at 0x7fa3642c8080>
slave_names: []
info: Device('/sys/devices/virtual/block/md125')
```

**Comment by cinquecento** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 247, in run
    threading.Thread.run(self, *args, **kwargs)
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/timezone.py", line 76, in time_initialize
    threadMgr.wait(THREAD_STORAGE)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 115, in wait
    self.raise_if_error(name)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 166, in raise_if_error
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 247, in run
    threading.Thread.run(self, *args, **kwargs)
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/blivet/osinstall.py", line 1123, in storageInitialize
    storage.reset()
  File "/usr/lib/python3.4/site-packages/blivet/blivet.py", line 279, in reset
    self.devicetree.populate(cleanupOnly=cleanupOnly)
  File "/usr/lib/python3.4/site-packages/blivet/devicetree.py", line 554, in populate
    self._populator.populate(cleanupOnly=cleanupOnly)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 1596, in populate
    self._populate()
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 1659, in _populate
    self.addUdevDevice(dev)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 715, in addUdevDevice
    device = self.addUdevMDDevice(info)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 363, in addUdevMDDevice
    self._addSlaveDevices(info)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 245, in _addSlaveDevices
    raise DeviceTreeError("no slaves found for device %s" % name)
blivet.errors.DeviceTreeError: no slaves found for device md125
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 247, in run
    threading.Thread.run(self, *args, **kwargs)
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/ui/gui/spokes/datetime_spoke.py", line 538, in _initialize
    threadMgr.wait(constants.THREAD_TIME_INIT)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 115, in wait
    self.raise_if_error(name)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 166, in raise_if_error
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 247, in run
    threading.Thread.run(self, *args, **kwargs)
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/timezone.py", line 76, in time_initialize
    threadMgr.wait(THREAD_STORAGE)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 115, in wait
    self.raise_if_error(name)
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 166, in raise_if_error
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/usr/lib64/python3.4/site-packages/pyanaconda/threads.py", line 247, in run
    threading.Thread.run(self, *args, **kwargs)
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/blivet/osinstall.py", line 1123, in storageInitialize
    storage.reset()
  File "/usr/lib/python3.4/site-packages/blivet/blivet.py", line 279, in reset
    self.devicetree.populate(cleanupOnly=cleanupOnly)
  File "/usr/lib/python3.4/site-packages/blivet/devicetree.py", line 554, in populate
    self._populator.populate(cleanupOnly=cleanupOnly)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 1596, in populate
    self._populate()
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 1659, in _populate
    self.addUdevDevice(dev)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 715, in addUdevDevice
    device = self.addUdevMDDevice(info)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 363, in addUdevMDDevice
    self._addSlaveDevices(info)
  File "/usr/lib/python3.4/site-packages/blivet/populator.py", line 245, in _addSlaveDevices
    raise DeviceTreeError("no slaves found for device %s" % name)
blivet.errors.DeviceTreeError: no slaves found for device md125
```

**Comment by haraldh** [comment]
Well, rd.md=0 only disables mdraid assembly in the initrd. You should probably add "nomdraid" also.

**Comment by cinquecento** [comment]
Although I have not found that option in the kernel documentation, I still tried, altogether with raid=noautodetect and rd.driver.blacklist=raid1, and none of them has the effect.

However neither can reproduce exception, not any more.
Thank for appearance.

**Comment by haraldh** [comment]
"nomdraid" is in the udev rules of mdadm, which take care of auto assembly.

**Comment by cinquecento** [comment]
Grepping the mdadm source I have not found any 'nomdraid' reference.
Besides, since this is a LiveCDVD, it is not intended to be a permanent change, but a temporary one for testing purposes, via kernel cmdline.

**Comment by haraldh** [comment]
Anyway, shouldn't this be fixed in anaconda? I guess, anaconda assembles raids on its own.

**Comment by cinquecento** [comment]
What I have experienced so far in the effort of making the RAID within, is only this message: 'NoneType' object has no attribute 'get_size'
