### ISSUE TITLE
IndexError getting signature

### ISSUE THREAD

**Issue by AndreasBackx** [rhinstaller/anaconda#830]
Ever since the version bump to 2.x on Anaconda I've been getting a lot of failed auto-formatting errors. I have no idea what causes them and would love to give you a reproducible a Python file but the files where this happens are relatively large. After trying to figure out what line might be the culprit, I failed. Here is the traceback anyhow:

```
INFO:Anaconda.anaconda_lib.callback:Calback de6228c7e54547e49147cb62a1210f99 came back with data but it's status was `timed_out` already
ERROR:root:list index out of range
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/Andreas/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 104, in process_message
ERROR:root:    callback(data)
ERROR:root:  File "/Users/Andreas/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/signatures.py", line 100, in prepare_data_status
ERROR:root:    self.signature = self.signature.splitlines()[2]
ERROR:root:IndexError: list index out of range
```

These are my settings with all of the comments stripped:

```javascript
{
    "anaconda_tooltip_theme": "dark",
    "enable_signatures_tooltip": false,
    "enable_docstrings_tooltip": false,
    "merge_signatures_and_doc": false,
    "auto_project_switch": true,
    "auto_python_builder_enabled": true,
    "jsonserver_debug": false,
    "jsonserver_debug_port": 9999,
    "python_interpreter": "python",
    "disable_anaconda_completion": false,
    "suppress_word_completions": false,
    "suppress_explicit_completions": true,
    "complete_parameters": false,
    "complete_all_parameters": false,
    "display_signatures": true,
    "auto_formatting": false,
    "auto_formatting_timeout": 3,
    "aggressive": 0,
    "autoformat_ignore": [],
    "autoformat_select": [],
    "mccabe_threshold": 7,
    "anaconda_linting": true,
    "anaconda_linting_behaviour": "always",
    "anaconda_linter_delay": 0.5,
    "anaconda_linter_persistent": false,
    "anaconda_gutter_marks": true,
    "anaconda_gutter_theme": "retina",
    "anaconda_linter_mark_style": "none",
    "anaconda_linter_underlines": true,
    "anaconda_linter_show_errors_on_save": false,
    "use_pylint": false,
    "pep8": true,
    "pep8_rcfile": false,
    "pep8_ignore": [],
    "pep8_max_line_length": 99,
    "pep8_error_levels": {
        "E": "W",
        "W": "V",
        "V": "V"
    },
    "pep257": false,
    "pep257_ignore": [
        "D209"
    ],
    "pyflakes_ignore": [],
    "pyflakes_explicit_ignore": [],
    "pylint_rcfile": false,
    "pylint_ignore": [],
    "pyflakes_ignore_import_*": true,
    "validate_imports": false,
    "anaconda_debug": false,
    "test_command": "tox",
    "test_delimeter": ":"
}
```

**Comment by jkonecny12** [comment]
Hi @AndreasBackx, are you sure you are talking about the right Anaconda? This is Anaconda - system installer for Fedora, RHEL and CentOS distributions.

**Comment by AndreasBackx** [comment]
Completely my bad, I had both repositories open and opened the issue on the wrong one.

![You didn't see anything](http://25.media.tumblr.com/tumblr_m8pvucvUSO1ry10fwo1_500.gif)
