### ISSUE TITLE
pyanaconda/install.py: ksdata.firstboot.setup() arg mismatch

### ISSUE THREAD

**Issue by bwann** [rhinstaller/anaconda#894]
In pyanaconda/install.py during a kickstart install, we're calling "ksdata.firstboot.setup(storage, ksdata, instClass)". Looks like the constructor for setup() in pykickstart/kickstart.py was changed to explicitly define arguments so we get the wrong number passed in

changed in:
https://github.com/rhinstaller/anaconda/commit/c6fccfecd20bcfe0fe407441d25622fce40da52e

```
22:46:48,501 DEBUG anaconda: running handleException
22:46:48,501 CRIT anaconda: Traceback (most recent call last):

  File "/usr/lib64/python3.5/site-packages/pyanaconda/threads.py", line 251, in run
    threading.Thread.run(self, *args, **kwargs)

  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/lib64/python3.5/site-packages/pyanaconda/install.py", line 194, in doInstall
    ksdata.firstboot.setup(storage, ksdata, instClass)

TypeError: setup() takes 3 positional arguments but 4 were given
```

**Comment by bwann** [comment]
nevermind, there's a PR for this over in https://github.com/rhinstaller/anaconda/pull/893
